[project]
name = "comfyui-queuecontrol"
version = "1.1.14"
description = "A ComfyUI extension helper for the bult-in Queue Manager that gives you more control over the job queue. You can pause/resume, change the run order, hold individual items, and manually save/load the entire queue to disk for backup that survives a restart/reboot. It also auto-saves/restores the current running queue in case of unintended crashes. This extension does not load any new dependencies."
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.9"

[project.urls]
Repository = "https://github.com/seeker-ktf/ComfyUI-QueueControl"

[tool.comfy]
PublisherId = "seeker-ktf"
DisplayName = "ComfyUI-QueueControl"
Icon = ""